# Generated by Django 5.0.1 on 2024-02-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0002_vendors_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.RemoveField(
            model_name="country",
            name="id",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="id",
        ),
        migrations.RemoveField(
            model_name="services",
            name="id",
        ),
        migrations.RemoveField(
            model_name="vendors",
            name="id",
        ),
        migrations.RemoveField(
            model_name="vendorservices",
            name="id",
        ),
        migrations.RemoveField(
            model_name="vendorservices",
            name="serviceName",
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="id",
        ),
        migrations.AddField(
            model_name="category",
            name="categoryId",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="country",
            name="countryId",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="customerId",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="services",
            name="serviceId",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="vendors",
            name="vendorId",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="vendorservices",
            name="services",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showout.services",
            ),
        ),
        migrations.AddField(
            model_name="vendorservices",
            name="vendorServicesId",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="wishListId",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
