# Generated by Django 5.0.1 on 2024-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0004_remove_vendors_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="username_field",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
