# Generated by Django 5.0.1 on 2024-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0004_remove_vendors_country_vendors_countryid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="categoryId",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="country",
            name="countryId",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="services",
            name="serviceId",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vendors",
            name="vendorId",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vendorservices",
            name="vendorServicesId",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="wishListId",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
