# Generated by Django 5.0.1 on 2024-02-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0005_customer_username_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="username_field",
        ),
        migrations.AddField(
            model_name="customer",
            name="mobile",
            field=models.IntegerField(null=True),
        ),
    ]
