# Generated by Django 5.0.1 on 2024-02-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0005_alter_category_categoryid_alter_country_countryid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendors",
            name="vendorId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
