# Generated by Django 5.0.1 on 2024-02-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0006_remove_customer_username_field_customer_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
