# Generated by Django 5.0.1 on 2024-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0006_alter_vendors_vendorid"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendors",
            name="last_login",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
