# Generated by Django 5.0.1 on 2024-02-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0007_alter_customer_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customerId",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
