# Generated by Django 5.0.1 on 2024-02-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0007_vendors_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorservices",
            name="vendorId",
            field=models.IntegerField(default=1),
        ),
    ]
