# Generated by Django 5.0.1 on 2024-02-26 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0008_vendorservices_vendorid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorservices",
            name="vendorId",
        ),
    ]
