# Generated by Django 5.0.1 on 2024-03-01 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0009_remove_vendorservices_vendorid"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorservices",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vendorservices",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showout.vendors",
            ),
        ),
        migrations.CreateModel(
            name="ReviewVendoreServices",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewVendoreServicesId",
                    models.AutoField(default=1, primary_key=True, serialize=False),
                ),
                ("vendorServicesId", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0)),
                ("review", models.CharField(max_length=500)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="showout.customer",
                    ),
                ),
                (
                    "vendorService",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="showout.vendorservices",
                    ),
                ),
            ],
        ),
    ]
