# Generated by Django 5.0.1 on 2024-02-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0009_alter_customer_customerid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="last_login",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
