# Generated by Django 5.0.1 on 2024-02-19 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0010_customer_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="customer",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
