# Generated by Django 5.0.1 on 2024-03-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0011_remove_wishlist_service_remove_wishlist_vendor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
