# Generated by Django 5.0.1 on 2024-02-19 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0011_remove_wishlist_customer_delete_customer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("firstName", models.CharField(max_length=200, null=True)),
                ("lastName", models.CharField(max_length=200, null=True)),
                ("email", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=200, null=True)),
                ("password", models.CharField(max_length=200)),
                ("buget", models.CharField(max_length=200)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "customerId",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="showout.country",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="wishlist",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showout.customer",
            ),
        ),
    ]
