# Generated by Django 5.0.1 on 2024-03-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0012_services_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="categoryId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="country",
            name="countryId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="services",
            name="serviceId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vendorservices",
            name="vendorServicesId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
