# Generated by Django 5.0.1 on 2024-03-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0013_alter_category_categoryid_alter_country_countryid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendors",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
