# Generated by Django 5.0.1 on 2024-03-01 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0014_vendors_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewvendoreservices",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showout.vendors",
            ),
        ),
    ]
