# Generated by Django 5.0.1 on 2024-03-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0015_reviewvendoreservices_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendors",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
