# Generated by Django 5.0.1 on 2024-03-01 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0016_vendors_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showout.vendors",
            ),
        ),
    ]
