# Generated by Django 5.0.1 on 2024-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0017_wishlist_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customerId",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reviewvendoreservices",
            name="rating",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="reviewvendoreservices",
            name="vendorServicesId",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="vendors",
            name="countryId",
            field=models.IntegerField(),
        ),
    ]
