# Generated by Django 5.0.1 on 2024-03-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0018_alter_customer_customerid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customerId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
