# Generated by Django 5.0.1 on 2024-03-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0019_alter_customer_customerid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                ("genderName", models.CharField(max_length=200, null=True)),
                ("generId", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="customer",
            name="country",
        ),
        migrations.AddField(
            model_name="customer",
            name="countryId",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="generId",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="vendors",
            name="generId",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="vendors",
            name="countryId",
            field=models.IntegerField(null=True),
        ),
    ]
