# Generated by Django 5.0.1 on 2024-03-03 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0020_gender_remove_customer_country_customer_countryid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="generId",
            new_name="genderId",
        ),
    ]
