# Generated by Django 5.0.1 on 2024-03-03 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0021_rename_generid_customer_genderid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gender",
            old_name="generId",
            new_name="genderId",
        ),
    ]
