# Generated by Django 5.0.1 on 2024-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0024_image_alter_vendors_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendors",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
    ]
