# Generated by Django 5.0.1 on 2024-03-03 13:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0026_alter_vendors_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendors",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/mac/Desktop/Django/business_in_the_box/static/images"
                ),
                upload_to="images",
            ),
        ),
    ]
