# Generated by Django 5.0.1 on 2024-03-08 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0031_vendorservices_budget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendors",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="vendors",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="vendors",
            name="linkedIn",
        ),
        migrations.RemoveField(
            model_name="vendors",
            name="tiktok",
        ),
        migrations.RemoveField(
            model_name="vendors",
            name="twitter",
        ),
    ]
