# Generated by Django 5.0.1 on 2024-03-15 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0034_vendors_pdfupload_vendorservices_pdfupload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="countryId",
        ),
        migrations.RemoveField(
            model_name="vendors",
            name="countryId",
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showout.country",
            ),
        ),
        migrations.AddField(
            model_name="vendors",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="showout.country",
            ),
        ),
    ]
