# Generated by Django 5.0.1 on 2024-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0035_remove_customer_countryid_remove_vendors_countryid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="salt",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
