# Generated by Django 5.0.1 on 2024-03-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0037_remove_customer_salt"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerRequests",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("requestId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="showout.customer",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="showout.vendors",
                    ),
                ),
                (
                    "vendorService",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="showout.vendorservices",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="WishList",
        ),
    ]
