# Generated by Django 5.0.1 on 2024-03-21 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0038_customerrequests_delete_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
    ]
