# Generated by Django 5.0.1 on 2024-03-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0039_remove_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="hashed_password",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
