# Generated by Django 5.0.1 on 2024-03-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showout', '0039_alter_vendors_image_alter_vendors_pdfupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='countryCode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
