# Generated by Django 5.0.1 on 2024-03-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0040_customer_hashed_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendors",
            name="hashed_password",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
