# Generated by Django 5.0.1 on 2024-03-23 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0041_alter_vendors_image_alter_vendors_pdfupload_and_more"),
        ("showout", "0041_vendors_hashed_password"),
    ]

    operations = []
