# Generated by Django 5.0.1 on 2024-03-23 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("showout", "0042_alter_vendors_image_alter_vendors_pdfupload_and_more"),
        ("showout", "0043_alter_vendors_image_alter_vendors_pdfupload_and_more"),
    ]

    operations = []
